### ISSUE TITLE
no method named define found for type ruru::Class in the current scope

### ISSUE THREAD

**Issue by NullVoxPopuli** [malept/thermite#10]
Hey, I'm just trying to follow and expand upon your rusty_blank example.

Here is my error
```
$ bundle exec rake thermite:build
checking for cargo... yes
/home/me/.cargo/bin/cargo build --release
   Compiling case_transform v0.1.0 (file:///home/me/Development/case_transform/ext/case_transform)
error: no method named `define` found for type `ruru::Class` in the current scope
  --> src/lib.rs:40:36
   |
40 |     Class::from_existing("String").define(|itself| {
   |                                    ^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
   = help: candidate #1: `use ruru::Object`

error: aborting due to previous error

error: Could not compile `case_transform`.

To learn more, run the command again with --verbose.
rake aborted!
Command failed with status (101): [/home/me/.cargo/bin/cargo bui...]
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:41:in `block in run_cargo'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:40:in `chdir'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:40:in `run_cargo'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/cargo.rb:58:in `run_cargo_build'
/home/me/.rvm/gems/ruby-2.3.0/gems/thermite-0.6.0/lib/thermite/tasks.rb:112:in `block in define_build_task'
/home/me/.rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/me/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/me/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => thermite:build
(See full trace by running task with --trace)
```

Here is the file that I'm trying to compile:
https://github.com/NullVoxPopuli/case_transform/blob/1473805bdf2789216f35fd13ea32061ac3609135/ext/case_transform/src/lib.rs#L40

**Comment by NullVoxPopuli** [comment]
```
$ rustc --version
rustc 1.13.0-nightly (32571c05c 2016-09-17)
$ cargo --version
cargo 0.13.0-nightly (9399229 2016-09-14)
```

**Comment by malept** [comment]
At the moment, rusty_blank only works with Ruru 0.7.x. I haven't updated it to work with 0.8.x yet.

Since this isn't Thermite-related, I'm closing the issue. (In the future, rusty_blank-related questions should go in the rusty_blank repo.)

**Comment by simon0191** [comment]
@NullVoxPopuli in version 0.8 the `define`trait was moved to `ruru::Object`. You only need to add Object to https://github.com/NullVoxPopuli/case_transform/blob/1473805bdf2789216f35fd13ea32061ac3609135/ext/case_transform/src/lib.rs#L15

like `use ruru::{Class,Object,RString}`
